### ISSUE TITLE
diary.jl file is created but nothing is written to it

### ISSUE THREAD

**Issue by crbinz** [dalum/Diary.jl#1]
I'm using Diary v0.1.1 with julia v1.5.0 on mac OS. Here's my Diary.jl config file:

```toml
author = "Chris Binz"
date_format = "E U d HH:MM"
diary_name = "diary.jl"
autocommit = true
directory_mode = false
blacklist = []
```

When I open a new Julia session (and stay in the `v1.5` environment), `Diary.jl` seems to be loaded correctly, and I can verify that `~/.julia/environments/v1.5/diary.jl` exists. However, when I type some commands into the REPL, nothing shows up in the file.
